### ISSUE TITLE
All variables use lower-case format

### ISSUE THREAD

**Issue by jonpas** [ArmA-Studio/ArmA.Studio#5]
Version: 0.1.6290.31151

Current format is `lowercase` (eg. `setunitloadout`).
Expected format is `camelCase` (eg. `setUnitLoadout`) as documented on wiki and shown inside Arma.

Aditionally it would be nice if auto-complete would ignore casing and you could type whichever of the above and it would still show proper `camelCase` commands.

**Comment by X39** [comment]
if you find a way to extract all informations out of the supportInfo command 🙈 
https://github.com/X39/ArmA.Studio/blob/master/ArmA.Studio/SqfDefinition.xml this is where those informations are received from
which is converted from supportInfo via regex

**Comment by jonpas** [comment]
I see. Would parsing the BI wiki via a script on top of that be ok?

**Comment by X39** [comment]
would also work
sadly, i neither have the network nor have the time right now to create such a script 🙈 

in case you want to do that, please also add the actual url to the sqfdefinitions.xml
will be needed later anyway :3

**Comment by jonpas** [comment]
Right, automatic wiki opening and all. :p

We have a few wiki parsers around for various editor plugins, can adapt that and make it work on top of the existing xml.

**Comment by X39** [comment]
feel free to modify the xml
can adapt to whatever is valid xml structuring

**Comment by dedmen** [comment]
Would also be nice to have a small description for every command. My plan is autocomplete like Atom has it. Also CBA and ACE stuff in seperate optional packets. We'll see how to implement such auto-complete packages. Would be nice if we later have a Plugin-Browser/Installer integrated. Like VS'es Extension browser.

**Comment by jonpas** [comment]
Yeah I was already thinking about CBA and ACE packages, we have scripts in the Atom language package for that too (faster ones than for BI wiki actually) but when I heard plugin support will be there I thought it would be better to do them as plugins at that time. Same for BI functions I'd say.

Can do description @dedmen as well, just like it is in Atom.

A good question is if we want everything that `supportInfo` includes, as some things are not actually documented, but all of them are pretty much very old and useless. I think relying on the wiki alone should be perfect. Thoughts?

**Comment by X39** [comment]
i personally do not care
supportInfo was the first way to go due to it providing me all informations i ever could need

what is essentially required at any time for SQF analysis later down the line is:
* command name
* command type (binary, unary, nullar)
* LType
* RType
* ReturnType

in case of array it might be interesting to get informations about the internias of the array too ... though ... it can be pretty difficult to represent that in XML and linting might not utilize it

also technically the command type type should also be included just to make sure that there is a general list of possible types available



and yes, obviously plugin support will also allow for custom linting and/or adding stuff to auto-complete
though ... first release with plugin possibility most likely wont contain the interfaces for that yet
